name: 'coverage'
on:
  pull_request:
    branches:
      - main
jobs:
  check:
    name: check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: yarn
        run: yarn
      - name: Run eslint for library
        run: yarn lint:lib:eslint
      # Skip until the following is corrected.
      # https://github.com/facebookexperimental/Recoil/issues/1902
      #       - name: Run type check for library
      #         run: yarn lint:lib:tsc
      - name: Run eslint for examples
        run: yarn lint:ex:eslint
      - name: Run jest
        run: yarn test
